### ISSUE TITLE
Provider plugins don't show the full name of ISP

### ISSUE THREAD

**Issue by tomac4t** [matomo-org/plugin-Provider#2]
- Matomo version: 3.13.12

I notice that Provider plugins don't show the full name of ISP: 

![2020-03-06_00-56](https://user-images.githubusercontent.com/47532693/76005490-0e456600-5f46-11ea-91f6-dbaf9a11adcc.png)

The example IP is 113.122.0.0, here is its information: 

```bash
$ mmdblookup -f GeoLite2-ASN.mmdb -i 113.122.0.0

  {
    "autonomous_system_number": 
      4134 <uint32>
    "autonomous_system_organization": 
      "No.31,Jin-rong Street" <utf8_string>
  }
```
Its full name is "No.31,Jin-rong Street" instead of "No" in GeoLite2-ASN. (Actually, it is an address rather than organization name... Maxmind error data.)

The related code is here, 

https://github.com/matomo-org/plugin-Provider/blob/ab708170e8879f8b782b1cf6a6ed475997ac857c/functions.php#L22-L31

I don't know the reason why `substr` part is existing, maybe it could be removed safely?

**Comment by tsteur** [comment]
Moved this issue into the provider plugin.

Not moving it into Matomo 4 for now as it's not just about removing this method. You'd basically break behaviour with already tracked data and all the data would change for our existing users and features like `row evolution` etc wouldn't work for them anymore. 

It may be fine to check that we don't exec the dot logic if the provider name has spaces or so. Feel free to create a PR @tomac4t if you can

**Comment by benjaminalamreeki** [comment]
@tsteur any action on this it's been a bug for nearly two years

**Comment by sgiehl** [comment]
@nasiralamreeki the referenced commit above should at least have improved that. Are you still having that issue?
