### ISSUE TITLE
File integrity check failed. Missing files

### ISSUE THREAD

**Issue by kimchristiansen** [matomo-org/plugin-Provider#20]
After installing the Provider PlugIn v.4.0.3 over the marketplace on a Matomo v. 4.5.0 installation, i get following warnings in the system check:

`Errors below may be due to a partial or failed upload of Matomo files.
--> Try to reupload all the Matomo files in BINARY mode. <--

Missing file: /matomo/plugins/Provider/lang/bs.json
Missing file: /matomo/plugins/Provider/lang/dv.json
Missing file: /matomo/plugins/Provider/lang/ga.json
Missing file: /matomo/plugins/Provider/lang/gu.json
Missing file: /matomo/plugins/Provider/lang/he.json
Missing file: /matomo/plugins/Provider/lang/hr.json
Missing file: /matomo/plugins/Provider/lang/hy.json
Missing file: /matomo/plugins/Provider/lang/ku.json
Missing file: /matomo/plugins/Provider/lang/lb.json
Missing file: /matomo/plugins/Provider/lang/nn.json
Missing file: /matomo/plugins/Provider/lang/te.json
File size mismatch: /matomo/plugins/Provider/lang/tr.json (expected length: 719, found: 718)
Missing file: /matomo/plugins/Provider/lang/tzm.json
Missing file: /matomo/plugins/Provider/lang/ur.json
File size mismatch: /matomo/plugins/Provider/Provider.php (expected length: 3479, found: 4328)
Missing file: /matomo/plugins/Provider/screenshots/Report.png` 

It seems like these files are missing in the latest release. In the master branch, these files are available.

**Comment by tsteur** [comment]
Thanks for reporting this @kimchristiansen . This should be resolved with the next Matomo 4.6 update. If that's happening again after Matomo 4.6 be great to comment again and we'll reopen this issue again and look further into it.
