### ISSUE TITLE
More infos about the source of provider detecting

### ISSUE THREAD

**Issue by matomoto** [matomo-org/plugin-Provider#41]
Hello,
please give us more infos about the source of provider detecting. What is the source of the provider list and how works the provider detecting? Works the plugin with requests to ... ?

**Comment by snake14** [comment]
Hi @matomoto . I believe that the provider information is already tracked by the core application and the Provider plugin simply adds a report that displays that information. There's a [FAQ that provides some more in depth information about visitor location tracking](https://matomo.org/faq/how-to/setting-up-accurate-visitors-geolocation/). I'm going to close this issue. Please feel free to search [Matomo's online knowledge base](https://forum.matomo.org/).
