### ISSUE TITLE
Empty label causes archiving to fail (`Label column not found in the table to add in addDataTable()`)

### ISSUE THREAD

**Issue by smokris** [matomo-org/plugin-Provider#47]
On our self-hosted Matomo instance, archiving started to fail a few days ago, with this backtrace:
<details><summary>Backtrace</summary>

```
Label column not found in the table to add in addDataTable(). Row: array ( 'label' => NULL, 2 => 1, 3 => '1', 4 => 1, 5 => '0', 6 => '1', 7 => '0', 11 => 1, 40 => 0, )
#0 /var/www/matomo/core/DataTable.php(667): Piwik\DataTable->aggregateRowWithLabel(Object(Piwik\DataTable\Row), false)
#1 /var/www/matomo/core/ArchiveProcessor.php(443): Piwik\DataTable->addDataTable(Object(Piwik\DataTable))
#2 /var/www/matomo/core/ArchiveProcessor.php(376): Piwik\ArchiveProcessor->getAggregatedDataTableMapFromBlobs(Object(Generator), NULL, NULL, 'Provider_hostna...')
#3 /var/www/matomo/core/ArchiveProcessor.php(232): Piwik\ArchiveProcessor->aggregateDataTableRecord('Provider_hostna...', NULL, NULL)
#4 /var/www/matomo/core/ArchiveProcessor/RecordBuilder.php(196): Piwik\ArchiveProcessor->aggregateDataTableRecords(Array, 500, NULL, NULL, NULL, NULL, false)
#5 /var/www/matomo/core/Plugin/Archiver.php(247): Piwik\ArchiveProcessor\RecordBuilder->buildForNonDayPeriod(Object(Piwik\ArchiveProcessor))
#6 /var/www/matomo/core/ArchiveProcessor/PluginsArchiver.php(186): Piwik\Plugin\Archiver->callAggregateMultipleReports()
#7 /var/www/matomo/core/ArchiveProcessor/Loader.php(310): Piwik\ArchiveProcessor\PluginsArchiver->callAggregateAllPlugins(33.0, 0, false)
#8 /var/www/matomo/core/ArchiveProcessor/Loader.php(185): Piwik\ArchiveProcessor\Loader->prepareAllPluginsArchive(33.0, 0)
#9 /var/www/matomo/core/ArchiveProcessor/Loader.php(164): Piwik\ArchiveProcessor\Loader->insertArchiveData(18.0, 0, false, NULL)
#10 /var/www/matomo/core/ArchiveProcessor/Loader.php(104): Piwik\ArchiveProcessor\Loader->prepareArchiveImpl(false)
#11 /var/www/matomo/core/Context.php(75): Piwik\ArchiveProcessor\Loader->Piwik\ArchiveProcessor\{closure}()
#12 /var/www/matomo/core/ArchiveProcessor/Loader.php(101): Piwik\Context::changeIdSite(7, Object(Closure))
#13 /var/www/matomo/plugins/CoreAdminHome/API.php(295): Piwik\ArchiveProcessor\Loader->prepareArchive(false)
#14 [internal function]: Piwik\Plugins\CoreAdminHome\API->archiveReports('7', Object(Piwik\Period\Week), '2023-08-14', false, false, false)
```

</details>

This is the row that appears to be causing the problem:
```
a:17:{i:0;a:3:{i:0;a:9:{s:5:"label";N;i:1;i:5;i:2;i:6;i:3;s:2:"12";i:39;i:0;i:4;i:2;i:5;s:2:"20";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:1;a:3:{i:0;a:9:{s:5:"label";s:7:"att.net";i:1;i:12;i:2;i:20;i:3;s:2:"43";i:39;i:0;i:4;i:4;i:5;s:4:"2669";i:6;s:1:"5";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:2;a:3:{i:0;a:9:{s:5:"label";s:11:"comcast.net";i:1;i:1;i:2;i:1;i:3;s:1:"1";i:39;i:0;i:4;i:1;i:5;s:1:"0";i:6;s:1:"1";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:3;a:3:{i:0;a:9:{s:5:"label";s:12:"direcway.com";i:1;i:2;i:2;i:2;i:3;s:1:"4";i:39;i:0;i:4;i:2;i:5;s:1:"8";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:4;a:3:{i:0;a:9:{s:5:"label";s:9:"exede.net";i:1;i:2;i:2;i:2;i:3;s:1:"4";i:39;i:0;i:4;i:2;i:5;s:2:"10";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:5;a:3:{i:0;a:9:{s:5:"label";s:15:"frontiernet.net";i:1;i:4;i:2;i:6;i:3;s:2:"11";i:39;i:0;i:4;i:2;i:5;s:2:"11";i:6;s:1:"1";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:6;a:3:{i:0;a:9:{s:5:"label";s:15:"intelliwave.com";i:1;i:1;i:2;i:1;i:3;s:1:"4";i:39;i:0;i:4;i:4;i:5;s:4:"1074";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:7;a:3:{i:0;a:9:{s:5:"label";s:2:"Ip";i:1;i:78;i:2;i:109;i:3;s:3:"230";i:39;i:0;i:4;i:8;i:5;s:4:"7696";i:6;s:2:"24";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:8;a:3:{i:0;a:9:{s:5:"label";s:14:"mycingular.net";i:1;i:7;i:2;i:7;i:3;s:2:"14";i:39;i:0;i:4;i:4;i:5;s:3:"157";i:6;s:1:"2";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:9;a:3:{i:0;a:9:{s:5:"label";s:9:"myvzw.com";i:1;i:14;i:2;i:16;i:3;s:2:"28";i:39;i:0;i:4;i:3;i:5;s:2:"95";i:6;s:1:"5";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:10;a:3:{i:0;a:9:{s:5:"label";s:8:"pldt.net";i:1;i:1;i:2;i:1;i:3;s:1:"7";i:39;i:0;i:4;i:7;i:5;s:2:"93";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:11;a:3:{i:0;a:9:{s:5:"label";s:6:"rr.com";i:1;i:4;i:2;i:4;i:3;s:1:"8";i:39;i:0;i:4;i:2;i:5;s:2:"20";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:12;a:3:{i:0;a:9:{s:5:"label";s:13:"sbcglobal.net";i:1;i:1;i:2;i:1;i:3;s:1:"4";i:39;i:0;i:4;i:4;i:5;s:2:"43";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:13;a:3:{i:0;a:9:{s:5:"label";s:10:"seovec.org";i:1;i:2;i:2;i:2;i:3;s:1:"4";i:39;i:0;i:4;i:2;i:5;s:2:"37";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:14;a:3:{i:0;a:9:{s:5:"label";s:12:"spectrum.com";i:1;i:2;i:2;i:2;i:3;s:1:"3";i:39;i:0;i:4;i:2;i:5;s:1:"6";i:6;s:1:"1";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:15;a:3:{i:0;a:9:{s:5:"label";s:14:"suddenlink.net";i:1;i:1;i:2;i:3;i:3;s:1:"6";i:39;i:0;i:4;i:2;i:5;s:2:"10";i:6;s:1:"0";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}i:16;a:3:{i:0;a:9:{s:5:"label";s:6:"vsi.ru";i:1;i:1;i:2;i:1;i:3;s:1:"1";i:39;i:0;i:4;i:1;i:5;s:1:"0";i:6;s:1:"1";i:7;s:1:"0";}i:1;a:0:{}i:3;N;}}
```

The first `label` is null, which fails the assertion in `addDataTable()`.

I was able to work around it by patching core to skip those rows:
```diff
--- core/ArchiveProcessor.php     2023-08-21 13:58:06.297601515 -0400
+++ core/ArchiveProcessor.php   2023-08-21 13:58:57.430092808 -0400
@@ -397,6 +397,9 @@
         foreach ($dataTableBlobs as $archiveDataRow) {
             $period = $archiveDataRow['date1'] . ',' . $archiveDataRow['date2'];
             $tableId = $archiveDataRow['name'] == $name ? null : $this->getSubtableIdFromBlobName($archiveDataRow['name']);
+            if (empty($archiveDataRow['label'])) {
+                continue;
+            }
 
             $blobTable = DataTable::fromSerializedArray($archiveDataRow['value']);
 
```
However, it looks like the underlying cause is that the Provider plugin is creating rows with empty labels, so I wonder if it would be better for the plugin to avoid creating the invalid rows in the first place.

<details><summary>System Check</summary>

#### PHP version >= 7.2.5:
 ✔ 8.2.9

#### PDO extension:
 ✔ 

#### PDO\MYSQL extension:
 ✔ 

#### MYSQLI extension:
 ✔ 

#### Other required extensions:
 ✔ zlib ✔ json ✔ filter ✔ hash ✔ session

#### Required functions:
 ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack

#### Required PHP configuration (php.ini):
 ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR = -1 OR >= 30

#### Directories with write access:
 ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c

#### Required Private Directories:
 ✔ All private directories are inaccessible from the internet.

#### Recommended Private Directories:
 ✔ All private directories are inaccessible from the internet.

#### 64-bit PHP Binary:
 ✔ 

#### Tracker status:
 ✔ 

#### Memory limit:
 ✔ 256M

#### Time zone:
 ✔ 

#### Open URL:
 ✔ curl

#### PageSpeed is turned off:
 ✔ 

#### GD > 2.x + FreeType (graphics):
 ✔ 

#### Other extensions:
 ✔ json ✔ libxml ✔ dom ✔ SimpleXML ✔ openssl

#### Other functions:
 ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file

#### Filesystem:
 ✔ 

#### Set up Cron - Managing processes via CLI:
 ✔ Ok

#### Last Successful Archiving Completion:
⚠ Error: Archiving last ran successfully on Friday, August 11, 2023 00:07:10 which is 10 days 17:43:34 ago.<br/><br/>Please check that you have setup a crontab calling the <code>core:archive</code> console command, and that you have configured a <code>MAILTO</code> to receive errors by email if archiving fails. You can also try to run the console command to archive your reports manually: <code>$DOC_ROOT/console --matomo-domain=matomo core:archive</code>. Learn more.

#### Database abilities:
 ✔ UTF8mb4 charset ⚠ Warning: LOAD DATA INFILE<br/>Hint: Using LOAD DATA INFILE by updating your PHP and MySQL software and ensuring your database user has the FILE privilege speeds up Matomo's archiving process a lot.<br/>You should fix this problem if your Matomo server tracks high-traffic websites (e.g. over 100,000 pages per month). ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level

#### Max Packet Size:
 ✔ 

#### Forced SSL Connection:
 ✔ 

#### Geolocation:
 ✔ geoip2php (continent_code, continent_name, country_code, country_name, region_name, city_name, lat, long)

#### Update over HTTPS:
 ✔ 

#### Mobile Messaging SMS Provider:
 not configured

#### Writable JavaScript Tracker ("/matomo.js"):
 ✔ 

#### Matomo Version:
 5.0.0-rc1

#### Matomo Update History:
 4.14.2,4.14.1,

#### Matomo Install Version:
 4.14.1

#### Latest Available Version:
 5.0.0-rc1

#### Is Git Deployment:
 0

#### PHP_OS:
 Linux

#### PHP_BINARY:
 /usr/sbin/php-fpm

#### PHP SAPI:
 fpm-fcgi

#### Timezone Version:
 2023.3

#### PHP Timezone:
 UTC

#### PHP Time:
 1692640245

#### PHP Datetime:
 2023-08-21 17:50:45

#### PHP INI max_execution_time:
 90

#### PHP INI post_max_size:
 256M

#### PHP INI max_input_vars:
 10000

#### Curl Version:
 7.76.1, OpenSSL/3.0.7

#### Suhosin Installed:
 0

#### DB Prefix:
 matomo_

#### DB Charset:
 utf8mb4

#### DB Adapter:
 MYSQLI

#### MySQL Version:
 10.5.16-MariaDB-log

#### Num Tables:
 163

#### Browser Segment Archiving Enabled:
 1

#### Development Mode Enabled:
 0

#### Internet Enabled:
 1

#### Multi Server Environment:
 0

#### Auto Update Enabled:
 1

#### Custom User Path:
 0

#### Custom Include Path:
 0

#### Release Channel:
 latest_beta

#### Plugins Activated:
 API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CoreVue, CustomAlerts 5.0.1, CustomDimensions, CustomJsTracker, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, Feedback, GeoIp2, Goals, Heartbeat, ImageGraph, Insights, Installation, Intl, IntranetMeasurable, LanguagesManager, Live, Login, LoginOIDC 5.0.0, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, ProfessionalServices, Provider 5.0.1, Proxy, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SegmentEditor, SitesManager, Tour, TrackingSpamPrevention 5.0.0, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize

#### Plugins Deactivated:
 DBStats, MobileAppMeasurable, TagManager

#### Server Info:
 Apache

#### Had visits in last 1 day:
 1

#### Had visits in last 3 days:
 1

#### Had visits in last 5 days:
 1

#### Archive Time Last Started:
 2023-08-21 15:24:06

#### Archive Time Last Finished:
 2023-08-11 00:07:10

#### User Agent:
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/116.0

#### Browser Language:
 en

#### Total Invalidation Count:
 210

#### In Progress Invalidation Count:
 3

#### Scheduled Invalidation Count:
 207

#### Earliest invalidation ts_started:
 2023-08-21 11:05:43

#### Latest invalidation ts_started:
 2023-08-21 11:24:09

#### Earliest invalidation ts_invalidated:
 2023-08-11 00:26:20

#### Latest invalidation ts_invalidated:
 2023-08-21 15:24:07

#### Number of segment invalidations:
 30

#### Number of plugin invalidations:
 0

#### Do Not Track enabled:
 1

</details>

**Comment by snake14** [comment]
Thank you @smokris for creating this detailed issue. You bring up a good point and I should probably consult our Core team as this is related to a recent core change.

@matomo-org/core-team what approach would you like to take with this issue? Should we fix it in the plugin, fix it in core, or both?

**Comment by diosmosis** [comment]
@snake14 this is due to the RecordBuilder change most likely, I'll take a closer look soon.
