### ISSUE TITLE
Matomo v5 compatibility 

### ISSUE THREAD

**Issue by jookk** [matomo-org/plugin-Provider#56]
I used your plugin with matomo for years., giving me some useful info.
But after v5 upgrade, its impossible to use Provider plugin anymore :(
Can you look at this issue?

**Comment by sgiehl** [comment]
@jookk Sorry to hear you are having trouble with the plugin.
What exactly is the problem? There should be a compatible version released already.

**Comment by jookk** [comment]
I tried to upgrade from v4.6.1 to v5 and there was warning, that plugins are deactivated, because of not compatibile with new version of matomo. But, today I removed it and reinstalled. Now its working fine. Thank you very much for your time :)
